name: Docker Image Sync to GHCR

on:
  # Executa quando acionado manualmente
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nome da imagem (ex: ethereum/client-go)'
        required: true
      image_tag:
        description: 'Tag da imagem (ex: release-1.10)'
        required: true
  
  # Executa diariamente às 2h da manhã
  schedule:
    - cron: '0 2 * * *'
  
  # Permite que seja acionado por outro workflow ou API
  repository_dispatch:
    types: [image_sync_requested]

jobs:
  sync-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Determinar imagem a sincronizar
        id: set-image-info
        run: |
          # Usa inputs do workflow_dispatch se disponíveis
          if [[ -n "${{ github.event.inputs.image_name }}" ]]; then
            IMAGE_NAME="${{ github.event.inputs.image_name }}"
            IMAGE_TAG="${{ github.event.inputs.image_tag }}"
          # Usa dados do repository_dispatch
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            IMAGE_NAME="${{ github.event.client_payload.image_name }}"
            IMAGE_TAG="${{ github.event.client_payload.image_tag }}"
          # Para execução agendada, verificar imagens predefinidas
          else
            # Lista de imagens a verificar na execução agendada
            IMAGE_NAME="ethereum/client-go"
            IMAGE_TAG="release-1.10"
          fi
          
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          
          # Para GHCR, mantemos o formato completo
          GHCR_IMAGE="ghcr.io/italoag/public/${IMAGE_NAME}:${IMAGE_TAG}"
          echo "GHCR_IMAGE=${GHCR_IMAGE}" >> $GITHUB_ENV
          
          # Log para depuração
          echo "Imagem definida: ${IMAGE_NAME}:${IMAGE_TAG}"
          echo "GHCR destino: ${GHCR_IMAGE}"
      
      - name: Verificar se a imagem existe no GHCR
        id: check-ghcr
        continue-on-error: true
        run: |
          # Extrair caminho da imagem para o GHCR
          if [[ "${{ env.IMAGE_NAME }}" == *"/"* ]]; then
            # Imagem com namespace (ex: ethereum/client-go)
            GHCR_PATH="italoag/public/${{ env.IMAGE_NAME }}"
          else
            # Imagem simples (ex: postgres)
            GHCR_PATH="italoag/public/${{ env.IMAGE_NAME }}"
          fi
          
          # Verificação HTTP para o manifesto da imagem no GHCR
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            "https://ghcr.io/v2/${GHCR_PATH}/manifests/${{ env.IMAGE_TAG }}")
          
          echo "Status HTTP GHCR: $STATUS_CODE"
          echo "URL verificada: https://ghcr.io/v2/${GHCR_PATH}/manifests/${{ env.IMAGE_TAG }}"
          
          if [[ "$STATUS_CODE" == "200" ]]; then
            echo "IMAGEM_EXISTE=true" >> $GITHUB_ENV
            echo "Imagem encontrada no GHCR"
          else
            echo "IMAGEM_EXISTE=false" >> $GITHUB_ENV
            echo "Imagem não encontrada no GHCR (Status: $STATUS_CODE)"
          fi
      
      - name: Verificar imagem no Docker Hub
        if: env.IMAGEM_EXISTE == 'false'
        id: check-dockerhub
        run: |
          # Determinar se a imagem é oficial ou de namespace personalizado
          if [[ "${{ env.IMAGE_NAME }}" == *"/"* ]]; then
            # Imagem com namespace personalizado (ex: ethereum/client-go)
            NAMESPACE=$(echo "${{ env.IMAGE_NAME }}" | cut -d'/' -f1)
            IMAGE_SHORT=$(echo "${{ env.IMAGE_NAME }}" | cut -d'/' -f2-)
            DOCKERHUB_REPO="${NAMESPACE}/${IMAGE_SHORT}"
            DOCKERHUB_SCOPE="repository:${DOCKERHUB_REPO}:pull"
          else
            # Imagem oficial (ex: postgres, nginx)
            DOCKERHUB_REPO="library/${{ env.IMAGE_NAME }}"
            DOCKERHUB_SCOPE="repository:${DOCKERHUB_REPO}:pull"
          fi
          
          echo "Verificando imagem no Docker Hub: ${DOCKERHUB_REPO}:${{ env.IMAGE_TAG }}"
          
          # Obter token de autenticação para o Docker Hub
          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=${DOCKERHUB_SCOPE}" | jq -r .token)
          
          if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
            echo "Erro ao obter token de autenticação para o Docker Hub"
            echo "Escopo usado: ${DOCKERHUB_SCOPE}"
            exit 1
          fi
          
          # Verificar se o manifesto existe no Docker Hub
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "https://registry-1.docker.io/v2/${DOCKERHUB_REPO}/manifests/${{ env.IMAGE_TAG }}")
          
          echo "Docker Hub Status: $STATUS_CODE"
          
          if [[ "$STATUS_CODE" == "200" || "$STATUS_CODE" == "307" ]]; then
            echo "DOCKERHUB_EXISTE=true" >> $GITHUB_ENV
            echo "DOCKERHUB_REPO=${DOCKERHUB_REPO}" >> $GITHUB_ENV
            echo "Imagem encontrada no Docker Hub: ${DOCKERHUB_REPO}:${{ env.IMAGE_TAG }}"
          else
            echo "DOCKERHUB_EXISTE=false" >> $GITHUB_ENV
            echo "Imagem não encontrada no Docker Hub: ${DOCKERHUB_REPO}:${{ env.IMAGE_TAG }} (Status: $STATUS_CODE)"
            exit 1
          fi
      
      # Usar a action oficial do Docker para login no GHCR
      - name: Login no GHCR
        if: env.IMAGEM_EXISTE == 'false' && env.DOCKERHUB_EXISTE == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Sincronizar imagem do Docker Hub para GHCR
        if: env.IMAGEM_EXISTE == 'false' && env.DOCKERHUB_EXISTE == 'true'
        run: |
          echo "Iniciando sincronização da imagem do Docker Hub para GHCR"
          
          # Depuração das variáveis de ambiente
          echo "Variáveis de ambiente:"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
          echo "DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}"
          echo "GHCR_IMAGE: ${{ env.GHCR_IMAGE }}"
          
          # Construir o nome completo da imagem no Docker Hub
          DOCKERHUB_FULL="${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}"
          
          # Puxar a imagem do Docker Hub
          echo "Puxando imagem do Docker Hub: ${DOCKERHUB_FULL}"
          docker pull ${DOCKERHUB_FULL}
          
          # Aplicar tag para GHCR
          echo "Aplicando tag para GHCR: ${{ env.GHCR_IMAGE }}"
          docker tag ${DOCKERHUB_FULL} ${{ env.GHCR_IMAGE }}
          
          # Enviar a imagem para o GHCR
          echo "Enviando imagem para o GHCR"
          docker push ${{ env.GHCR_IMAGE }}
          
          echo "Sincronização completa para: ${{ env.GHCR_IMAGE }}"
      
      - name: Resultado da verificação
        run: |
          if [[ "${{ env.IMAGEM_EXISTE }}" == "true" ]]; then
            echo "A imagem já existe no GHCR, nenhuma ação necessária."
          elif [[ "${{ env.DOCKERHUB_EXISTE }}" != "true" ]]; then
            echo "Erro: A imagem não foi encontrada no Docker Hub."
          else
            echo "Imagem sincronizada com sucesso do Docker Hub para o GHCR."
          fi
